apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-staging

bases:
  - ../../base

images:
  - name: shinobislayer/actions
    newName: shinobislayer/actions
    newTag: latest

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: actions-app
    count: 2
