apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-staging

resources:
  - ../../base

images:
  - name: shinobislayer/actions
    newName: shinobislayer/actions
    newTag: latest

namePrefix: staging-

labels:
  - pairs:
      environment: staging

replicas:
  - name: actions-app
    count: 2

patches:
  - path: ingress-patch.yaml
