apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-prod

resources:
  - ../../base
  - namespace.yaml

images:
  - name: shinobislayer/actions
    newName: shinobislayer/actions
    newTag: latest

namePrefix: prod-

labels:
  - pairs:
      environment: prod

replicas:
  - name: actions-app
    count: 3

patches:
  - path: ingress-patch.yaml
