apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-prod

bases:
  - ../../base

images:
  - name: shinobislayer/actions
    newName: shinobislayer/actions
    newTag: latest

namePrefix: prod-

commonLabels:
  environment: prod

replicas:
  - name: actions-app
    count: 3

resources:
  - namespace.yaml
