apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-dev

resources:
  - ../../base

images:
  - name: shinobislayer/actions
    newName: shinobislayer/actions
    newTag: 2025.12.021-MAIN

namePrefix: dev-

labels:
  - pairs:
      environment: dev
