apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-dev

bases:
  - ../../base

images:
  - name: shinobislayer/actions
    newName: shinobislayer/actions
    newTag: 2025.12.020-MAIN

namePrefix: dev-

commonLabels:
  environment: dev
